In [1]:
import os
import sys

PROJECT_ROOT = os.path.abspath("..")
if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)

print(PROJECT_ROOT)

d:\Property Intelligence Platform

In [2]:
import numpy as np
import pandas as pd

In [3]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [4]:

from src.data.ingestion import load_data
df = load_data("../data/merged/gurgaon_properties.csv")

Dataset loaded successfully.
Rows: 3961
Columns: 20

In [5]:
df.sample(5)

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
1169,3 BHK Flat in Sector 79 Gurgaon,flat,mapsko mount ville,1.40,9395.0,1490.0,Carpet area: 1490 (138.43 sq.m.),3,3,3,not available,"Sector 79 Gurgaon, Gurgaon, Haryana",2.0,North,0 to 1 Year Old,"['Huda Metro Station (Gurugram)', 'Sapphire 83...","Park , pool facing . Apartment above gym , club .","['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '3 Ge...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area5 out of 5', 'Construction5 out of..."
471,3 BHK Flat in Nirvana Country,flat,the close south,3.25,12810.0,2537.0,Carpet area: 2537 (235.7 sq.m.),3,4,3+,servant room,"Nirvana Country, Gurgaon, Haryana",4.0,South-East,10+ Year Old,"['Fresco Market', 'Emerald Plaza', 'Tagore Pub...",Preference location. Facing the front garden e...,"['6 Fan', '1 Fridge', '1 Exhaust Fan', '3 Geys...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area5 out of 5', 'Construction4.5 out ..."
4,6 Bedroom House for sale in Sector 46 Gurgaon,house,rwa sector 46,4.50,24390.0,1845.0,Plot area 204(170.57 sq.m.)Built Up area: 206 ...,6,6,3+,store room,"8 Marla Built Up As Bmt, Gf,ff, 6bhk Demand-4....",3.0,North-East,5 to 10 Year Old,"['Axis bank ATM', 'State bank of india ATM', '...",Looking for a independent house in gurgaon's p...,"['5 Wardrobe', '1 Water Purifier', '13 Fan', '...","['Private Garden / Terrace', 'High Ceiling Hei...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1862,2 BHK Flat in Sector 95 Gurgaon,flat,ramsons kshitij,0.35,5495.0,637.0,Built Up area: 637 (59.18 sq.m.),2,2,0,not available,"Sector 95 Gurgaon, Gurgaon, Haryana",5.0,NaN,undefined,"['Bangali Clinic', 'Yadav Clinic', 'Dr. J. S. ...","2 bath, unfurnished, 5th floor (Of 15), at sec...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4.5 out of..."
2465,2 BHK Flat in Sohna,flat,eldeco accolade,0.78,5422.0,1439.0,Super Built up area 1457(135.36 sq.m.),2,2,2,study room,"0001, Sohna, Gurgaon, Haryana",7.0,North,1 to 5 Year Old,"['Global City Centre', 'Sohna Road', 'Damdama ...","On the road society, good connectivity to delh...","['2 Bed', '2 Wardrobe', '2 Fan', '1 Exhaust Fa...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction4.5 out ..."

In [6]:
df.shape

(3961, 20)

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3961 entries, 0 to 3960
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3961 non-null   object
 1   property_type    3961 non-null   object
 2   society          3960 non-null   object
 3   price            3941 non-null   float64
 4   price_per_sqft   3941 non-null   float64
 5   area             3941 non-null   float64
 6   areaWithType     3961 non-null   object
 7   bedRoom          3961 non-null   int64
 8   bathroom         3961 non-null   int64
 9   balcony          3961 non-null   object
 10  additionalRoom   3961 non-null   object
 11  address          3950 non-null   object
 12  floorNum         3940 non-null   float64
 13  facing           2784 non-null   object
 14  agePossession    3960 non-null   object
 15  nearbyLocations  3754 non-null   object
 16  description      3961 non-null   object
 17  furnishDetails   2929 non-null   object
 18  features         3252 non-null   object
 19  rating           3511 non-null   object
dtypes: float64(4), int64(2), object(14)
memory usage: 619.0+ KB

In [9]:
df.isnull().sum()

property_name         0
property_type         0
society               1
price                20
price_per_sqft       20
area                 20
areaWithType          0
bedRoom               0
bathroom              0
balcony               0
additionalRoom        0
address              11
floorNum             21
facing             1177
agePossession         1
nearbyLocations     207
description           0
furnishDetails     1032
features            709
rating              450
dtype: int64

In [10]:
df.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,4 Bedroom House for sale in Sector 92 Gurgaon,house,sare crescent parc royal greens phase 1,0.85,4877.0,1743.0,Built Up area: 1743 (161.93 sq.m.),4,4,3,not available,"Sec -92 Gurgaon, Sector 92 Gurgaon, Gurgaon, H...",4.0,NaN,undefined,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",4bhk penthouse for new property in sare cresce...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,4 BHK Flat in Sector 92 Gurgaon,flat,sare green parc phase 3,1.08,5150.0,2097.0,Super Built up area 2090(194.17 sq.m.),4,4,2,servant room,NaN,16.0,NaN,0 to 1 Year Old,"['Huda Metro Station', 'Sector Road', 'Delhi-J...",Only end user and buyers to contact. Flat in r...,NaN,"['Security / Fire Alarm', 'Intercom Facility',...","['Safety3 out of 5', 'Lifestyle4 out of 5', 'E..."
2,4 Bedroom House for sale in Sector 33 Gurgaon,house,unitech uniworld resorts,8.00,11428.0,7000.0,Plot area 7000(650.32 sq.m.),4,4,3+,"pooja room,servant room,study room,store room","Sector 33 Gurgaon, Gurgaon, Haryana",2.0,West,10+ Year Old,"['Rajiv Chowk Mosque', 'Icici bank ATM', 'Stan...",Why buy in unitech the villas?\nJust minutes a...,NaN,"['Private Garden / Terrace', 'False Ceiling Li...","['Environment3 out of 5', 'Safety4 out of 5', ..."
3,3 BHK Flat in Sector 67A Gurgaon,flat,ireo the corridors,1.60,9264.0,1727.0,Super Built up area 1727(160.44 sq.m.)Carpet a...,3,3,2,store room,"000, Sector 67A Gurgaon, Gurgaon, Haryana",3.0,North,0 to 1 Year Old,"['Huda Metro Station (Gurugram)', 'Paras Trini...",Brokers please excuse\n3 bhk +store room resid...,"['3 Wardrobe', '1 Water Purifier', '4 Fan', '1...","['Water purifier', 'Security / Fire Alarm', 'P...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
4,6 Bedroom House for sale in Sector 46 Gurgaon,house,rwa sector 46,4.50,24390.0,1845.0,Plot area 204(170.57 sq.m.)Built Up area: 206 ...,6,6,3+,store room,"8 Marla Built Up As Bmt, Gf,ff, 6bhk Demand-4....",3.0,North-East,5 to 10 Year Old,"['Axis bank ATM', 'State bank of india ATM', '...",Looking for a independent house in gurgaon's p...,"['5 Wardrobe', '1 Water Purifier', '13 Fan', '...","['Private Garden / Terrace', 'High Ceiling Hei...","['Environment4 out of 5', 'Safety4 out of 5', ..."

In [11]:
df['property_name'].value_counts()

property_name
2 BHK Flat in Sohna                                                                      125
3 BHK Flat in Sector 102 Gurgaon                                                          76
3 BHK Flat in Sector 65 Gurgaon                                                           57
3 BHK Flat in Sector 92 Gurgaon                                                           53
3 BHK Flat in Sector 69 Gurgaon                                                           51
2 BHK Flat in Sector 85 Gurgaon                                                           49
3 BHK Flat in Sector 83 Gurgaon                                                           47
3 BHK Flat in Sector 81 Gurgaon                                                           45
3 BHK Flat in Sector 79 Gurgaon                                                           44
3 BHK Flat in Sector 109 Gurgaon                                                          44
2 BHK Flat in Sector 107 Gurgaon                                                          38
3 BHK Flat in Sector 90 Gurgaon                                                           38
3 BHK Flat in Sector 37D Gurgaon                                                          38
3 BHK Flat in Sector 70 Gurgaon                                                           36
3 BHK Flat in Sector 85 Gurgaon                                                           36
2 BHK Flat in Sector 79 Gurgaon                                                           35
3 BHK Flat in Sector 86 Gurgaon                                                           34
3 BHK Flat in Sector 37C Gurgaon                                                          33
4 BHK Flat in Sector 92 Gurgaon                                                           33
2 BHK Flat in Sector 95 Gurgaon                                                           33
4 BHK Flat in Sector 69 Gurgaon                                                           32
3 BHK Flat in Sector 104 Gurgaon                                                          31
2 BHK Flat in Sector 102 Gurgaon                                                          30
3 BHK Flat in Sector 108 Gurgaon                                                          30
3 BHK Flat in Sector 67 Gurgaon                                                           30
3 BHK Flat in Sector-33 Sohna                                                             29
4 BHK Flat in Sector 90 Gurgaon                                                           29
3 BHK Flat in Sector 89 Gurgaon                                                           29
3 BHK Flat in Sector 56 Gurgaon                                                           26
2 BHK Flat in Sector 89 Gurgaon                                                           25
4 BHK Flat in Sector 85 Gurgaon                                                           25
2 BHK Flat in Sector 81 Gurgaon                                                           25
2 BHK Flat in Sector 86 Gurgaon                                                           24
3 BHK Flat in Sector 61 Gurgaon                                                           23
2 BHK Flat in Sector 90 Gurgaon                                                           23
3 BHK Flat in Sector 113 Gurgaon                                                          23
3 BHK Flat in Sector 84 Gurgaon                                                           22
3 BHK Flat in Sector 70A Gurgaon                                                          22
2 BHK Flat in Sector 68 Gurgaon                                                           22
2 BHK Flat in Sector 84 Gurgaon                                                           21
3 BHK Flat in Nirvana Country                                                             20
3 BHK Flat in Sohna                                                                       20
4 Bedroom House for sale in Sector 109 Gurgaon                                            19
3 BHK Flat in Sector 49 Gurgaon                                                           19
3 BHK Flat in Sector 107 Gurgaon                                                          19
2 BHK Flat in Sector 99A Gurgaon                                                          19
2 BHK Flat in Sector 37C Gurgaon                                                          18
3 BHK Flat in Sector 77 Gurgaon                                                           18
2 BHK Flat in Sector 65 Gurgaon                                                           18
3 BHK Flat in Sector 106 Gurgaon                                                          18
2 BHK Flat in Sector-33 Sohna                                                             18
3 BHK Flat in Sector 48 Gurgaon                                                           18
2 BHK Flat in Sector 108 Gurgaon                                                          18
2 BHK Flat in Sector 61 Gurgaon                                                           17
3 BHK Flat in Sector 66 Gurgaon                                                           17
4 Bedroom House for sale in Sector 48 Gurgaon                                             17
4 BHK Flat in Sector 72 Gurgaon                                                           17
5 Bedroom House for sale in DLF Phase 2                                                   16
2 BHK Flat in Sector 103 Gurgaon                                                          16
2 BHK Flat in Sector 37D Gurgaon                                                          15
2 BHK Flat in Sector 70A Gurgaon                                                          15
5 Bedroom House for sale in DLF Phase 1                                                   15
4 BHK Flat in Sector 81 Gurgaon                                                           15
3 BHK Flat in Sector 103 Gurgaon                                                          15
4 BHK Flat in Sector 104 Gurgaon                                                          15
2 BHK Flat in Sector 104 Gurgaon                                                          15
1 BHK Flat in Sohna                                                                       14
3 BHK Flat in Sector 54 Gurgaon                                                           14
4 BHK Flat in Sector 65 Gurgaon                                                           14
2 BHK Flat in Sector 82 Gurgaon                                                           13
3 BHK Flat in Sector 82 Gurgaon                                                           13
2 BHK Flat in Sector 83 Gurgaon                                                           13
2 BHK Flat in Sector 92 Gurgaon                                                           13
3 BHK Flat in Sector 88A Gurgaon                                                          13
2 BHK Flat in Sector 74 Gurgaon                                                           13
4 Bedroom House for sale in Nirvana Country                                               13
2 BHK Flat in Palam Vihar                                                                 12
3 BHK Flat in Sector 95 Gurgaon                                                           12
4 BHK Flat in Sector 37D Gurgaon                                                          12
5 Bedroom House for sale in Sector 109 Gurgaon                                            12
3 BHK Flat in Sector 99A Gurgaon                                                          12
3 BHK Flat in Sector 1 Imt Manesar                                                        11
3 BHK Flat in Sector 71 Gurgaon                                                           11
3 BHK Flat in Sector 78 Gurgaon                                                           10
2 BHK Flat in Sector 113 Gurgaon                                                          10
3 BHK Flat in Sector 22 Gurgaon                                                           10
1 BHK Flat in Sector 95 Gurgaon                                                           10
2 BHK Flat in Sector 67A Gurgaon                                                          10
5 Bedroom House for sale in Nirvana Country                                               10
4 BHK Flat in Sector 110 Gurgaon                                                          10
3 BHK Flat in Palam Vihar                                                                 10
5 Bedroom House for sale in Sector 66 Gurgaon                                             10
4 BHK Flat in Sector 56 Gurgaon                                                           10
3 BHK Flat in Sector 53 Gurgaon                                                            9
4 Bedroom House for sale in DLF Phase 1                                                    9
3 BHK Flat in Sector 67A Gurgaon                                                           9
2 BHK Flat in Sector 69 Gurgaon                                                            9
4 BHK Flat in Sector 111 Gurgaon                                                           9
3 BHK Flat in Sector 112 Gurgaon                                                           9
2 BHK Flat in Sector 95A Gurgaon                                                           9
2 BHK Flat in Sector 88A Gurgaon                                                           9
2 BHK Flat in Sector 70 Gurgaon                                                            9
5 Bedroom House for sale in Sector 33 Gurgaon                                              9
2 BHK Flat in Sector 93 Gurgaon                                                            8
2 BHK Flat in Sector 77 Gurgaon                                                            8
2 BHK Flat in Sector 106 Gurgaon                                                           8
3 BHK Flat in Sector 63A Gurgaon                                                           8
4 BHK Flat in Sector 48 Gurgaon                                                            8
3 BHK Flat in Sector 72 Gurgaon                                                            8
4 Bedroom House for sale in Palam Vihar                                                    8
4 BHK Flat in Sector 106 Gurgaon                                                           8
3 BHK Flat in Sector 82A Gurgaon                                                           8
2 BHK Flat in Sector 71 Gurgaon                                                            8
4 BHK Flat in Sector 113 Gurgaon                                                           8
1 BHK Flat in Sector 56 Gurgaon                                                            8
2 BHK Flat in Sector 99 Gurgaon                                                            8
4 BHK Flat in Sector 67 Gurgaon                                                            8
2 BHK Flat in Sector 3 Gurgaon                                                             7
2 BHK Flat in Sector 78 Gurgaon                                                            7
3 BHK Flat in Dwarka Expressway Gurgaon                                                    7
4 BHK Flat in DLF Phase 5                                                                  7
4 BHK Flat in Sector 112 Gurgaon                                                           7
4 BHK Flat in Sector 62 Gurgaon                                                            7
3 BHK Flat in Sector 111 Gurgaon                                                           7
4 Bedroom House for sale in Sector 66 Gurgaon                                              7
2 BHK Flat in Sector 63A Gurgaon                                                           7
4 BHK Flat in Sector 103 Gurgaon                                                           7
3 BHK Flat in Sector 63 Gurgaon                                                            7
3 BHK Flat in Sector 1A IMT Manesar                                                        7
4 Bedroom House for sale in Sector 70A Gurgaon                                             7
6 Bedroom House for sale in DLF Phase 1                                                    7
3 Bedroom House for sale in Nirvana Country                                                7
4 BHK Flat in Sector 109 Gurgaon                                                           7
9 Bedroom House for sale in DLF Phase 2                                                    7
4 BHK Flat in Sector 91 Gurgaon                                                            7
4 BHK Flat in Sector 108 Gurgaon                                                           7
3 BHK Flat in Sector 76 Gurgaon                                                            7
4 BHK Flat in Sector 82 Gurgaon                                                            6
4 Bedroom House for sale in Sushant Lok Phase 3                                            6
4 BHK Flat in Sector 70 Gurgaon                                                            6
4 BHK Flat in Sector 54 Gurgaon                                                            6
3 BHK Flat in Sector 68 Gurgaon                                                            6
3 Bedroom House for sale in Rajendra Park                                                  6
3 BHK Flat in Sector 59 Gurgaon                                                            6
2 BHK Flat in Sector 22 Gurgaon                                                            6
2 BHK Flat in Sector 33 Gurgaon                                                            6
4 BHK Flat in Sector 9A Gurgaon                                                            6
4 BHK Flat in Sector 99 Gurgaon                                                            6
3 BHK Flat in Sector 36 Sohna                                                              6
4 Bedroom House for sale in Sector 82 Gurgaon                                              6
2 BHK Flat in Laxman Vihar                                                                 6
4 BHK Flat in Sector 82A Gurgaon                                                           6
3 BHK Flat in DLF Phase 4                                                                  6
2 BHK Flat in Sector 66 Gurgaon                                                            6
2 BHK Flat in DLF Phase 4                                                                  6
3 BHK Flat in DLF Phase 5                                                                  6
4 BHK Flat in Sector 102 Gurgaon                                                           6
4 BHK Flat in Gwal Pahari                                                                  6
4 BHK Flat in Sector 84 Gurgaon                                                            6
2 BHK Flat in Sector 36A Gurgaon                                                           6
4 Bedroom House for sale in DLF Phase 3                                                    6
4 Bedroom House for sale in DLF Phase 2                                                    5
4 BHK Flat in Sector 63 Gurgaon                                                            5
5 Bedroom House for sale in Laxman Vihar                                                   5
4 BHK Flat in Sector 60 Gurgaon                                                            5
3 BHK Flat in Gwal Pahari                                                                  5
1 BHK Flat in Palam Vihar                                                                  5
3 BHK Flat in Sector 89 A Gurgaon                                                          5
2 BHK Flat in Sector 112 Gurgaon                                                           5
3 Bedroom House for sale in Sector 49 Gurgaon                                              5
3 Bedroom House for sale in Laxman Vihar                                                   5
3 BHK Flat in Sector 74 Gurgaon                                                            5
4 BHK Flat in Sector 66 Gurgaon                                                            5
2 BHK Flat in Sector 62 Gurgaon                                                            5
4 BHK Flat in Sector 86 Gurgaon                                                            5
1 BHK Flat in Sector 36A Gurgaon                                                           5
5 Bedroom House for sale in Sector 14 Gurgaon                                              5
2 Bedroom House for sale in Laxman Vihar                                                   5
1 BHK Flat in Sector 71 Gurgaon                                                            5
3 BHK Flat in Sector 60 Gurgaon                                                            5
2 BHK Flat in Sector 91 Gurgaon                                                            5
3 BHK Flat in Sector 43 Gurgaon                                                            4
2 BHK Flat in Sector 76 Gurgaon                                                            4
3 BHK Flat in Sector 47 Gurgaon                                                            4
4 Bedroom House for sale in Sector 26 Gurgaon                                              4
4 BHK Flat in Sector 49 Gurgaon                                                            4
3 BHK Flat in Sushant Lok Phase 1                                                          4
3 Bedroom House for sale in Laxman Vihar Phase 2                                           4
4 Bedroom House for sale in DLF Phase 4                                                    4
3 Bedroom House for sale in Sector 48 Gurgaon                                              4
5 BHK Flat in Sector 110 Gurgaon                                                           4
5 BHK Flat in Sector 49 Gurgaon                                                            4
6 Bedroom House for sale in Uppals Southend                                                4
4 BHK Flat in Sector 52 Gurgaon                                                            4
2 Bedroom House for sale in Laxman Vihar Phase 2                                           4
4 Bedroom House for sale in Sector 31 Gurgaon                                              4
3 BHK Flat in Sector 9A Gurgaon                                                            4
5 Bedroom House for sale in Sushant Lok Phase 1                                            4
6 Bedroom House for sale in Palam Vihar                                                    4
4 BHK Flat in Sector 83 Gurgaon                                                            4
4 Bedroom House for sale in Sector 54 Gurgaon                                              4
3 BHK Flat in Sector 80 Gurgaon                                                            4
2 BHK Flat in Sector 60 Gurgaon                                                            4
3 Bedroom House for sale in Sector 4 Gurgaon                                               4
6 Bedroom House for sale in DLF Phase 2                                                    4
3 Bedroom House for sale in Sector 14 Gurgaon                                              4
1 BHK Flat in Sector 104 Gurgaon                                                           4
16 Bedroom House for sale in DLF Phase 1                                                   4
3 BHK Flat in Mehrauli Gurgaon Road                                                        4
4 BHK Flat in Sector 50 Gurgaon                                                            4
1 Bedroom House for sale in Sushant Lok Phase 1                                            3
2 BHK Flat in Sector 111 Gurgaon                                                           3
6 Bedroom House for sale in Sushant Lok Phase 3                                            3
2 BHK Flat in Sector 88B Gurgaon                                                           3

In [12]:
df.insert(loc=3,column='sector',value=df['property_name'].str.split('in').str.get(1).str.replace('Gurgaon','').str.strip())

In [13]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,4 Bedroom House for sale in Sector 92 Gurgaon,house,sare crescent parc royal greens phase 1,Sector 92,0.85,4877.0,1743.0,Built Up area: 1743 (161.93 sq.m.),4,4,3,not available,"Sec -92 Gurgaon, Sector 92 Gurgaon, Gurgaon, H...",4.0,NaN,undefined,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",4bhk penthouse for new property in sare cresce...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,4 BHK Flat in Sector 92 Gurgaon,flat,sare green parc phase 3,Sector 92,1.08,5150.0,2097.0,Super Built up area 2090(194.17 sq.m.),4,4,2,servant room,NaN,16.0,NaN,0 to 1 Year Old,"['Huda Metro Station', 'Sector Road', 'Delhi-J...",Only end user and buyers to contact. Flat in r...,NaN,"['Security / Fire Alarm', 'Intercom Facility',...","['Safety3 out of 5', 'Lifestyle4 out of 5', 'E..."
2,4 Bedroom House for sale in Sector 33 Gurgaon,house,unitech uniworld resorts,Sector 33,8.00,11428.0,7000.0,Plot area 7000(650.32 sq.m.),4,4,3+,"pooja room,servant room,study room,store room","Sector 33 Gurgaon, Gurgaon, Haryana",2.0,West,10+ Year Old,"['Rajiv Chowk Mosque', 'Icici bank ATM', 'Stan...",Why buy in unitech the villas?\nJust minutes a...,NaN,"['Private Garden / Terrace', 'False Ceiling Li...","['Environment3 out of 5', 'Safety4 out of 5', ..."
3,3 BHK Flat in Sector 67A Gurgaon,flat,ireo the corridors,Sector 67A,1.60,9264.0,1727.0,Super Built up area 1727(160.44 sq.m.)Carpet a...,3,3,2,store room,"000, Sector 67A Gurgaon, Gurgaon, Haryana",3.0,North,0 to 1 Year Old,"['Huda Metro Station (Gurugram)', 'Paras Trini...",Brokers please excuse\n3 bhk +store room resid...,"['3 Wardrobe', '1 Water Purifier', '4 Fan', '1...","['Water purifier', 'Security / Fire Alarm', 'P...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
4,6 Bedroom House for sale in Sector 46 Gurgaon,house,rwa sector 46,Sector 46,4.50,24390.0,1845.0,Plot area 204(170.57 sq.m.)Built Up area: 206 ...,6,6,3+,store room,"8 Marla Built Up As Bmt, Gf,ff, 6bhk Demand-4....",3.0,North-East,5 to 10 Year Old,"['Axis bank ATM', 'State bank of india ATM', '...",Looking for a independent house in gurgaon's p...,"['5 Wardrobe', '1 Water Purifier', '13 Fan', '...","['Private Garden / Terrace', 'High Ceiling Hei...","['Environment4 out of 5', 'Safety4 out of 5', ..."

In [14]:
df['sector'] = df['sector'].str.lower()

In [15]:
df['sector'].value_counts()

sector
sohna                                                        163
sector 102                                                   113
sector 85                                                    110
sector 92                                                    104
sector 69                                                     94
sector 81                                                     90
sector 65                                                     90
sector 90                                                     90
sector 109                                                    88
sector 79                                                     80
sector 83                                                     69
sector 37d                                                    68
sector 86                                                     67
sector 104                                                    66
sector 107                                                    60
sector 108                                                    59
sector 95                                                     57
sector 56                                                     57
sector 48                                                     56
sector 89                                                     56
sector 70a                                                    54
nirvana country                                               53
sector 37c                                                    53
sector 70                                                     53
sector 84                                                     51
sector-33 sohna                                               51
palam vihar                                                   50
sector 67                                                     48
sector 66                                                     46
sector 103                                                    45
sector 113                                                    43
dlf phase 2                                                   43
dlf phase 1                                                   43
sector 61                                                     42
sector 82                                                     42
sector 106                                                    38
sector 49                                                     36
sector 99a                                                    32
sushant lok phase 1                                           31
sector 68                                                     30
sector 77                                                     29
sector 72                                                     29
sector 54                                                     27
laxman vihar                                                  27
sector 71                                                     27
dlf phase 4                                                   26
sector 112                                                    24
sector 33                                                     23
sector 88a                                                    23
sector 67a                                                    22
sector 111                                                    22
dlf phase 3                                                   22
sector 82a                                                    20
sector 22                                                     20
sector 78                                                     19
sector 74                                                     18
sector 63a                                                    18
sector 91                                                     17
sector 62                                                     17
sector 110                                                    16
sushant lok phase 3                                           16
sector 99                                                     16
sector 63                                                     15
sector 60                                                     15
sector 14                                                     15
rajendra park                                                 14
sector 53                                                     14
sector 3                                                      14
sector 1 imt manesar                                          14
sector 76                                                     14
gwal pahari                                                   14
sector 52                                                     14
dlf phase 5                                                   14
sector 46                                                     13
sector 36a                                                    13
laxman vihar phase 2                                          13
sector 93                                                     12
uppals southend                                               12
sector 31                                                     12
sector 50                                                     12
sector 38                                                     12
sector 39                                                     12
sohna road                                                    12
ashok vihar phase 3 extension                                 11
sector 47                                                     11
sector 9a                                                     11
sector 1a imt manesar                                         10
sector 7                                                      10
sector 95a                                                     9
south city 1                                                   9
ashok vihar phase 2                                            9
sector 4                                                       9
sector 55                                                      9
c block sushant lok phase 1                                    8
sector 40                                                      8
sector 43                                                      8
sector 57                                                      8
sector 89 a                                                    8
sector 59                                                      8
malibu town                                                    8
sector 10a                                                     8
palam vihar extension                                          8
mehrauli  road                                                 8
dwarka expressway                                              8
sector 26                                                      7
surat nagar 1                                                  7
mianwali colony                                                7
sector 36 sohna                                                7
sector 11                                                      7
sector 51                                                      7
sector 58                                                      7
new colony                                                     7
jacobpura                                                      6
sector 5                                                       6
rajiv nagar                                                    6
ashok vihar                                                    6
jyoti park                                                     6
sector 1                                                       6
ansal plaza                                                    5
saraswati vihar                                                5
sector 80                                                      5
sushant lok phase 2                                            5
manesar                                                        5
sector 30                                                      5
new palam vihar                                                5
sector 28                                                      5
greenwood city                                                 5
chakkarpur                                                     5
subhash nagar                                                  5
sector 105                                                     5
sector 2                                                       5
sector 23a                                                     5
arjun nagar                                                    5
sector 9                                                       5
dayanand colony                                                5
baldev nagar                                                   4
sector 17                                                      4
ravi nagar                                                     4
adarsh nagar                                                   4
sector 3a                                                      4
devilal colony                                                 4
krishna colony                                                 4
madanpuri                                                      4
sector 45                                                      4
bhim nagar                                                     4
sector 6                                                       4
sector 12                                                      4
imt manesar                                                    4
shivpuri                                                       4
vishnu garden                                                  4
dharam colony                                                  4
shivaji nagar                                                  4
surya vihar                                                    4
valley view estate                                             4
suncity                                                        4
garhi harsaru                                                  4
sector 36                                                      4
bhondsi                                                        4
new                                                            4
sector 12a                                                     4
patel nagar                                                    3
sector 17a                                                     3
a block sushant lok phase 1                                    3
prem nagar                                                     3
sector 88b                                                     3
laxmi garden                                                   3
sector 15                                                      3
gandhi nagar                                                   3
sector 73                                                      3
sector 8                                                       3
shakti nagar                                                   3
b block sushant lok phase 1                                    3
mg road                                                        3
sector 23                                                      3
maruti kunj                                                    3
sector 27                                                      3
sector 110 a                                                   3
sector 17b                                                     3
mohan nagar                                                    2
west rajiv nagar                                               2
sispal vihar                                                   2
acharya puri                                                   2
new basti                                                      2
sector 15 part 1                                               2
iffco chowk                                                    2
, delhi ncr                                                    2
sector-2 sohna                                                 2
sector 41                                                      2
sushant lok                                                    2
farukhnagar                                                    2
sector 32                                                      2
sheetla colony                                                 2
rosewood                                                       2
ambience island                                                2
samaspur                                                       2
nars                                                           2
sector 21                                                      2
lajpat nagar                                                   2
new palam vihar phase 2                                        2
shanti nagar                                                   2
sector-11 sohna                                                2
bhawani enclave                                                2
sector 24                                                      2
surat nagar                                                    2
new palam vihar phase 1                                        2
surat nagar phase 2                                            2
bissar                                                         2
sohna  road                                                    2
golf course ext road                                           2
shankar vihar                                                  2
golf course road                                               2
block a surya vihar                                            2
sector 15 part 2                                               2
hira nagar                                                     2
daulatabad                                                     2
pratap nagar                                                   2
manohar nagar                                                  2
mayfield garden                                                2
faridabad road                                                 2
rajiv chowk                                                    2
godrej aria , sector 79 ,                                      1
ashok vihar phase i                                            1
gopal nagar, garhi ghasita, sonipat                            1
sector 9b                                                      1
sai kunj                                                       1
sector 4 urban estate                                          1
garauli kalan                                                  1
ats marigold                                                   1
sec 3 bhim vihar part 1 bhimgher kheri                         1
begampur khatola                                               1
om nagar                                                       1
near sector 1 market                                           1
block h ashok vihar phase iii extension                        1
near nand hospital                                             1
sector 17c                                                     1
sadar bazar                                                    1
rattan garden                                                  1
kanahi                                                         1
heritage city                                                  1
jacobpura near sadar bazar                                     1
sector 5 chowk                                                 1
anand garden, sector-105                                       1
sector-35 sohna                                                1
mahalaxmi garden, rajendra place                               1
vir nagar                                                      1
naharpur rupa                                                  1
shivji park colony                                             1
park view                                                      1
laxmna vihar, phase 2                                          1
dhankot                                                        1
sector 37a                                                     1
hno 13 sagar enclave sura                                      1
mahavir pura                                                   1
civil l                                                        1
nirvana country pocket h                                       1
old delhi road, opp sector-14                                  1
sector 37b                                                     1
saroop garden rajendra park                                    1
ram nagar                                                      1
jat colony,fazilpur/taj nagar road                             1
kheri                                                          1
urban estate, sector 5                                         1
sector 42                                                      1
udyog vihar phase 1                                            1
rajiv colony                                                   1
alipur                                                         1
ansal's palam vihar                                            1
sultanpur                                                      1
near khandsa road                                              1
b1 block sector 57                                             1
ravi nager basai road                                          1
carterpuri village                                             1
damdma                                                         1
v block dlf phase 3                                            1
sector 21a faridabad                                           1
block g sector-57                                              1
bhimgarh kheri phase 3                                         1
lucknow                                                        1
tekchand nagar                                                 1
devi lal colony gali no 12 gurgaon nr omkar public school      1
khandsa                                                        1
ashok vihar phase 3                                            1
south city                                                     1
cyber city                                                     1
new colony, sector 7                                           1
hsiidc plot sector 1 imt manesar                               1
sector 13                                                      1
saraswati enclave                                              1
sector-5 sohna                                                 1
near pataudi chowk                                             1
part 3 sector 5                                                1
sector-5 sheetla colony                                        1
bhora kalan                                                    1
pataudi road                                                   1
new jyoti park                                                 1
bptp                                                           1
sector-7 hous                                                  1
g block dlf city phase 1                                       1
near euro                                                      1
laxman vihar, railway road,                                    1
huda saraswati vihar                                           1
Name: count, dtype: int64

In [16]:
df['sector'] = df['sector'].str.replace('dharam colony','sector 12')
df['sector'] = df['sector'].str.replace('krishna colony','sector 7')
df['sector'] = df['sector'].str.replace('suncity','sector 54')
df['sector'] = df['sector'].str.replace('prem nagar','sector 13')
df['sector'] = df['sector'].str.replace('mg road','sector 28')
df['sector'] = df['sector'].str.replace('gandhi nagar','sector 28')
df['sector'] = df['sector'].str.replace('laxmi garden','sector 11')
df['sector'] = df['sector'].str.replace('shakti nagar','sector 11')

In [17]:
df['sector'] = df['sector'].str.replace('baldev nagar','sector 7')
df['sector'] = df['sector'].str.replace('shivpuri','sector 7')
df['sector'] = df['sector'].str.replace('garhi harsaru','sector 17')
df['sector'] = df['sector'].str.replace('imt manesar','manesar')
df['sector'] = df['sector'].str.replace('adarsh nagar','sector 12')
df['sector'] = df['sector'].str.replace('shivaji nagar','sector 11')
df['sector'] = df['sector'].str.replace('bhim nagar','sector 6')
df['sector'] = df['sector'].str.replace('madanpuri','sector 7')

In [18]:
df['sector'] = df['sector'].str.replace('saraswati vihar','sector 28')
df['sector'] = df['sector'].str.replace('arjun nagar','sector 8')
df['sector'] = df['sector'].str.replace('ravi nagar','sector 9')
df['sector'] = df['sector'].str.replace('vishnu garden','sector 105')
df['sector'] = df['sector'].str.replace('bhondsi','sector 11')
df['sector'] = df['sector'].str.replace('surya vihar','sector 21')
df['sector'] = df['sector'].str.replace('devilal colony','sector 9')
df['sector'] = df['sector'].str.replace('valley view estate','gwal pahari')
df['sector'] = df['sector'].str.replace('mehrauli  road','sector 14')
df['sector'] = df['sector'].str.replace('jyoti park','sector 7')
df['sector'] = df['sector'].str.replace('ansal plaza','sector 23')
df['sector'] = df['sector'].str.replace('dayanand colony','sector 6')
df['sector'] = df['sector'].str.replace('sushant lok phase 2','sector 55')
df['sector'] = df['sector'].str.replace('chakkarpur','sector 28')
df['sector'] = df['sector'].str.replace('greenwood city','sector 45')
df['sector'] = df['sector'].str.replace('subhash nagar','sector 12')

In [19]:
df['sector'] = df['sector'].str.replace('sohna road road','sohna road')
df['sector'] = df['sector'].str.replace('malibu town','sector 47')
df['sector'] = df['sector'].str.replace('surat nagar 1','sector 104')
df['sector'] = df['sector'].str.replace('new colony','sector 7')
df['sector'] = df['sector'].str.replace('mianwali colony','sector 12')
df['sector'] = df['sector'].str.replace('jacobpura','sector 12')
df['sector'] = df['sector'].str.replace('rajiv nagar','sector 13')
df['sector'] = df['sector'].str.replace('ashok vihar','sector 3')
df['sector'] = df['sector'].str.replace('dlf phase 1','sector 26')
df['sector'] = df['sector'].str.replace('nirvana country','sector 50')
df['sector'] = df['sector'].str.replace('palam vihar','sector 2')
df['sector'] = df['sector'].str.replace('dlf phase 2','sector 25')
df['sector'] = df['sector'].str.replace('sushant lok phase 1','sector 43')
df['sector'] = df['sector'].str.replace('laxman vihar','sector 4')
df['sector'] = df['sector'].str.replace('dlf phase 4','sector 28')
df['sector'] = df['sector'].str.replace('dlf phase 3','sector 24')

In [20]:
df['sector'] = df['sector'].str.replace('sushant lok phase 3','sector 57')
df['sector'] = df['sector'].str.replace('dlf phase 5','sector 43')
df['sector'] = df['sector'].str.replace('rajendra park','sector 105')
df['sector'] = df['sector'].str.replace('uppals southend','sector 49')
df['sector'] = df['sector'].str.replace('sohna','sohna road')
df['sector'] = df['sector'].str.replace('ashok vihar phase 3 extension','sector 5')
df['sector'] = df['sector'].str.replace('south city 1','sector 41')
df['sector'] = df['sector'].str.replace('ashok vihar phase 2','sector 5')

In [21]:
a = df['sector'].value_counts()[df['sector'].value_counts() >= 3]
df = df[df['sector'].isin(a.index)]

In [22]:
df['sector'].value_counts()

sector
sohna road                    163
sector 102                    113
sector 85                     110
sector 92                     104
sector 69                      94
sector 65                      90
sector 81                      90
sector 90                      90
sector 109                     88
sector 79                      80
sector 104                     73
sector 83                      69
sector 37d                     68
sector 86                      67
sector 50                      65
sector 107                     60
sector 108                     59
sector 56                      57
sector 95                      57
sector 48                      56
sector 89                      56
sector 2                       55
sector 70a                     54
sector 43                      53
sector 70                      53
sector 37c                     53
sector 84                      51
sector-33 sohna road           51
sector 26                      50
sector 49                      48
sector 67                      48
sector 28                      47
sector 66                      46
sector 103                     45
sector 113                     43
sector 25                      43
sector 61                      42
sector 82                      42
sector 7                       39
sector 106                     38
sector 4                       36
sector 99a                     32
sector 54                      31
sector 12                      30
sector 68                      30
sector 72                      29
sector 77                      29
sector 71                      27
sector 24                      24
sector 112                     24
sector 57                      24
sector 14                      23
sector 88a                     23
sector 105                     23
sector 33                      23
sector 67a                     22
sector 111                     22
sector 11                      21
sector 3                       20
sector 22                      20
sector 82a                     20
sector 47                      19
sector 78                      19
sector 63a                     18
sector 74                      18
gwal pahari                    18
sector 91                      17
sector 62                      17
sector 99                      16
sector 110                     16
sector 63                      15
sector 60                      15
sector 52                      14
sector 1 manesar               14
sector 76                      14
sector 53                      14
sector 55                      14
sector 4 phase 2               13
sector 6                       13
sector 46                      13
sector 9                       13
sector 36a                     13
sector 38                      12
sector 39                      12
sector 93                      12
sohna road road                12
sector 31                      12
sector 41                      11
sector 9a                      11
sector 3 phase 3 extension     11
sector 13                      10
sector 1a manesar              10
sector 3 phase 2                9
manesar                         9
sector 95a                      9
sector 45                       9
dwarka expressway               8
sector 89 a                     8
c block sector 43               8
sector 2 extension              8
sector 10a                      8
sector 59                       8
sector 8                        8
sector 40                       8
sector 17                       8
sector 23                       8
sector 51                       7
sector 36 sohna road            7
sector 58                       7
sector 5                        6
sector 21                       6
sector 1                        6
sector 23a                      5
new sector 2                    5
sector 80                       5
sector 30                       5
sector 3a                       4
new                             4
sector 36                       4
sector 12a                      4
sector 27                       3
sector 17a                      3
maruti kunj                     3
a block sector 43               3
patel nagar                     3
sector 88b                      3
sector 17b                      3
sector 15                       3
sector 110 a                    3
sector 73                       3
b block sector 43               3
Name: count, dtype: int64

In [23]:
df['sector'] = df['sector'].str.replace('sector 95a','sector 95')
df['sector'] = df['sector'].str.replace('sector 23a','sector 23')
df['sector'] = df['sector'].str.replace('sector 12a','sector 12')
df['sector'] = df['sector'].str.replace('sector 3a','sector 3')
df['sector'] = df['sector'].str.replace('sector 110 a','sector 110')
df['sector'] = df['sector'].str.replace('patel nagar','sector 15')
df['sector'] = df['sector'].str.replace('a block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('maruti kunj','sector 12')
df['sector'] = df['sector'].str.replace('b block sector 43','sector 43')

In [24]:
df['sector'] = df['sector'].str.replace('sector-33 sohna road','sector 33')
df['sector'] = df['sector'].str.replace('sector 1 manesar','manesar')
df['sector'] = df['sector'].str.replace('sector 4 phase 2','sector 4')
df['sector'] = df['sector'].str.replace('sector 1a manesar','manesar')
df['sector'] = df['sector'].str.replace('c block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('sector 89 a','sector 89')
df['sector'] = df['sector'].str.replace('sector 2 extension','sector 2')
df['sector'] = df['sector'].str.replace('sector 36 sohna road','sector 36')

In [25]:
df[df['sector'] == 'new']

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
1181,4 BHK Flat in New Gurgaon,flat,dlf 76,new,4.00,11428.0,3500.0,Carpet area: 3500 (325.16 sq.m.),4,4,2,"study room,servant room","New Gurgaon, Gurgaon, Haryana",4.0,NaN,Jun 2027,"['Shri Balaji Hospital and Trauma Center', 'S....",This lovely 4 bhk apartment/flat in new gurgao...,"['6 Wardrobe', '1 Fridge', '8 Fan', '1 Exhaust...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...",NaN
1763,4 BHK Flat in New Gurgaon,flat,sare homes,new,0.85,4786.0,1776.0,Super Built up area 1776(165 sq.m.),4,4,3,not available,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,5 to 10 Year Old,"['Columbia Asia Hospital', 'Apex Multi Special...",Located in the popular residential address of ...,[],NaN,NaN
2479,2 BHK Flat in New Gurgaon,flat,green court,new,0.38,5507.0,690.0,Carpet area: 690 (64.1 sq.m.),2,2,1,not available,"New Gurgaon, Gurgaon, Haryana",7.0,NaN,Under Construction,"['Ing bank ATM', 'Dcb bank ATM', 'Indus ind ba...",We are the proud owners of this 2 bhk apartmen...,[],"['Intercom Facility', 'Lift(s)', 'Maintenance ...",NaN
3566,2 BHK Flat in New Gurgaon,flat,takshila heights sector 37 c,new,0.67,5583.0,1200.0,Super Built up area 1200(111.48 sq.m.),2,2,2,not available,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,1 to 5 Year Old,"['Shri Balaji Hospital and Trauma Center', 'S....",Check out this 2 bhk apartment for sale in tak...,[],"['Lift(s)', 'Swimming Pool', 'Visitor Parking'...",NaN

In [26]:
sector_mapping = {
    "takshila heights sector 37 c": "sector 37",
    "sare homes": "sector 92",
    "green court": "sector 90",
    "dlf 76": "sector 76"
}
mask = df["sector"] == "new"

df.loc[mask, "sector"] = (
    df.loc[mask, "society"]
      .map(sector_mapping)
      .fillna(df.loc[mask, "sector"])
)

In [27]:
df[df['sector'] == 'new']

Empty DataFrame
Columns: [property_name, property_type, society, sector, price, price_per_sqft, area, areaWithType, bedRoom, bathroom, balcony, additionalRoom, address, floorNum, facing, agePossession, nearbyLocations, description, furnishDetails, features, rating]
Index: []

In [28]:
df[df['sector'] == 'new sector 2']

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
1864,2 BHK Flat in New Palam Vihar,flat,my home,new sector 2,0.28,3166.0,884.0,Carpet area: 900 (83.61 sq.m.),2,1,1,others,"F 150/b, New Palam Vihar, Gurgaon, Haryana",2.0,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","2 bhk room with wooden coverd ,1 drawing room,...","['3 Wardrobe', '5 Light', '1 Chimney', '1 Modu...","['Water Storage', 'Park']","['Environment4 out of 5', 'Safety4 out of 5', ..."
2021,2 Bedroom House for sale in New Palam Vihar,house,my home,new sector 2,0.34,12592.0,270.0,Plot area 270(25.08 sq.m.),2,2,2,not available,"Ez-19 A, New Palam Vihar, Gurgaon, Haryana",3.0,West,5 to 10 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",There are availability of various facilities l...,"['1 Wardrobe', '3 Fan', '6 Light', 'No AC', 'N...","['Water Storage', 'Park', 'Visitor Parking']","['Environment4 out of 5', 'Lifestyle4 out of 5..."
2702,2 BHK Flat in New Palam Vihar,flat,my home,new sector 2,0.22,4400.0,500.0,Carpet area: 500 (46.45 sq.m.),2,2,1,not available,"New Palam Vihar, Gurgaon, Haryana",1.0,NaN,0 to 1 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",Cctv surveillance are provided here. There is ...,"['3 Fan', '1 Exhaust Fan', '15 Light', '1 Modu...",NaN,"['Safety4 out of 5', 'Lifestyle4 out of 5', 'E..."
3176,2 BHK Flat in New Palam Vihar,flat,ompee k s residency,new sector 2,1.60,26936.0,594.0,Carpet area: 66 (55.18 sq.m.),2,2,2,not available,"New Palam Vihar, Gurgaon, Haryana",1.0,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",We are the proud owners of this 2 bhk apartmen...,NaN,NaN,"['Environment4 out of 5', 'Safety4 out of 5', ..."
3816,3 Bedroom House for sale in New Palam Vihar,house,independent,new sector 2,1.00,8796.0,1137.0,Plot area 120(100.34 sq.m.)Built Up area: 120 ...,3,2,2,pooja room,"Q-148, New Palam Vihar, Phase-2, Near Royal Oa...",1.0,North,10+ Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","Ground and first floor, Ground floor: Ground f...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."

In [29]:
mask = (
    (df["sector"] == "new sector 2") &
    (df["property_name"].str.contains("New Palam Vihar", case=False, na=False))
)

df.loc[mask, "sector"] = "sector 110"

In [31]:
df[df['sector'] == 'new']

Empty DataFrame
Columns: [property_name, property_type, society, sector, price, price_per_sqft, area, areaWithType, bedRoom, bathroom, balcony, additionalRoom, address, floorNum, facing, agePossession, nearbyLocations, description, furnishDetails, features, rating]
Index: []

In [32]:
df.shape

(3803, 21)

In [33]:
df.duplicated().sum()

np.int64(0)

In [34]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,4 Bedroom House for sale in Sector 92 Gurgaon,house,sare crescent parc royal greens phase 1,sector 92,0.85,4877.0,1743.0,Built Up area: 1743 (161.93 sq.m.),4,4,3,not available,"Sec -92 Gurgaon, Sector 92 Gurgaon, Gurgaon, H...",4.0,NaN,undefined,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",4bhk penthouse for new property in sare cresce...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,4 BHK Flat in Sector 92 Gurgaon,flat,sare green parc phase 3,sector 92,1.08,5150.0,2097.0,Super Built up area 2090(194.17 sq.m.),4,4,2,servant room,NaN,16.0,NaN,0 to 1 Year Old,"['Huda Metro Station', 'Sector Road', 'Delhi-J...",Only end user and buyers to contact. Flat in r...,NaN,"['Security / Fire Alarm', 'Intercom Facility',...","['Safety3 out of 5', 'Lifestyle4 out of 5', 'E..."
2,4 Bedroom House for sale in Sector 33 Gurgaon,house,unitech uniworld resorts,sector 33,8.00,11428.0,7000.0,Plot area 7000(650.32 sq.m.),4,4,3+,"pooja room,servant room,study room,store room","Sector 33 Gurgaon, Gurgaon, Haryana",2.0,West,10+ Year Old,"['Rajiv Chowk Mosque', 'Icici bank ATM', 'Stan...",Why buy in unitech the villas?\nJust minutes a...,NaN,"['Private Garden / Terrace', 'False Ceiling Li...","['Environment3 out of 5', 'Safety4 out of 5', ..."
3,3 BHK Flat in Sector 67A Gurgaon,flat,ireo the corridors,sector 67a,1.60,9264.0,1727.0,Super Built up area 1727(160.44 sq.m.)Carpet a...,3,3,2,store room,"000, Sector 67A Gurgaon, Gurgaon, Haryana",3.0,North,0 to 1 Year Old,"['Huda Metro Station (Gurugram)', 'Paras Trini...",Brokers please excuse\n3 bhk +store room resid...,"['3 Wardrobe', '1 Water Purifier', '4 Fan', '1...","['Water purifier', 'Security / Fire Alarm', 'P...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
4,6 Bedroom House for sale in Sector 46 Gurgaon,house,rwa sector 46,sector 46,4.50,24390.0,1845.0,Plot area 204(170.57 sq.m.)Built Up area: 206 ...,6,6,3+,store room,"8 Marla Built Up As Bmt, Gf,ff, 6bhk Demand-4....",3.0,North-East,5 to 10 Year Old,"['Axis bank ATM', 'State bank of india ATM', '...",Looking for a independent house in gurgaon's p...,"['5 Wardrobe', '1 Water Purifier', '13 Fan', '...","['Private Garden / Terrace', 'High Ceiling Hei...","['Environment4 out of 5', 'Safety4 out of 5', ..."

In [35]:
# features to drop -> property_name, address, description, rating
df.drop(columns=['property_name', 'address', 'description', 'rating'],inplace=True)

In [36]:
df.sample(5)

,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,floorNum,facing,agePossession,nearbyLocations,furnishDetails,features
3428,flat,sobha city,sector 108,3.75,14938.0,2510.0,Super Built up area 2343(217.67 sq.m.),3,3,2,servant room,16.0,North-East,0 to 1 Year Old,"['Dwarka Sector 21', 'Dwarka Expressway', 'Vas...","['1 Fan', '1 Light', 'No AC', 'No Bed', 'No Ch...","['Intercom Facility', 'Lift(s)', 'Swimming Poo..."
1895,flat,adani m2k oyster grande,sector 102,2.50,7817.0,3198.0,Super Built up area 3198(297.1 sq.m.)Built Up ...,4,5,3+,"servant room,pooja room",10.0,North-East,1 to 5 Year Old,"['WTC Plaza', 'Star Mall', 'Dwarka Expy, Dhanw...","['6 Fan', '1 Exhaust Fan', '1 Stove', '5 Light...","['Centrally Air Conditioned', 'Water purifier'..."
692,house,independent,sector 26,20.00,44444.0,4500.0,Plot area 500(418.06 sq.m.),5,7,3+,"servant room,pooja room",3.0,West,1 to 5 Year Old,"['Guru dronacharya metro station', 'Dlf phase ...","['1 Water Purifier', '16 Fan', '1 Fridge', '1 ...","['Security / Fire Alarm', 'Private Garden / Te..."
0,house,sare crescent parc royal greens phase 1,sector 92,0.85,4877.0,1743.0,Built Up area: 1743 (161.93 sq.m.),4,4,3,not available,4.0,NaN,undefined,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...","['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN
758,flat,emaar mgf emerald estate,sector 65,1.75,12544.0,1395.0,Super Built up area 1395(129.6 sq.m.)Carpet ar...,3,3,3,servant room,10.0,North-East,1 to 5 Year Old,"['Sector 53-54 Metro Station', 'Central Plaza ...","['1 Exhaust Fan', '3 Geyser', '7 Light', '1 Ch...","['Security / Fire Alarm', 'Intercom Facility',..."

In [37]:
df.duplicated().sum()

np.int64(122)

In [38]:
# Create the folder if it doesn't exist
os.makedirs("../data/cleaned", exist_ok=True)

df.to_csv("../data/cleaned/gurgaon_properties_cleaned_v1.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!